#+TITLE:      HNScieCloud Testing Period 2
#+AUTHOR:     Daniil Pintjuk
#+EMAIL:      daniil.pintjuk@cern.ch
#+HTML_HEAD:      <style type="text/css">#outline-container-introduction{ clear:both; }</style>
#+LATEX_HEADER: \usepackage{graphicx}
#+LATEX_HEADER: \usepackage{fancyhdr}
#+LATEX_HEADER: \pagestyle{fancy}
#+LATEX_HEADER: \fancyhf{}
#+LATEX_HEADER: \rhead{}
#+LATEX_HEADER: \lhead{\includegraphics[height=1.5cm]{logo}}
#+LATEX_HEADER: \rfoot{Page \thepage}
#+LATEX_HEADER: \renewcommand{\headrulewidth}{0pt}


#+LATEX_HEADER: \usepackage{geometry}
#+LATEX_HEADER: \geometry{ a4paper, headheight=1.5cm,}
#+LATEX_HEADER: \usepackage[dvipsnames]{xcolor}
#+LATEX_HEADER: \usepackage{sectsty} 
#+LATEX_HEADER: \subsectionfont{\color{NavyBlue}}

#+LANGUAGE:   en
#+BIBLIOGRAPHY: refs plain


* TODO Introduction
During my time att CERN join the HNScieCloud PCP project. A Pre commercial Procurmet tender to develop a cloud platform to support high proframnce computting and big data capabilitis for scientific research.

When I joined the project was moving into the stage of testing protote platforms from the 3 contractos: 

1) T-systems, Huawell, Cyfront, Divia
2) IBM
3) RHEA Group, T-systems, exoscale, SixSq

My contribution was going to be to preform 2 of CERN's tests sets of the prototypes.

The prototypes ware requiered to provide Object Storage (OBS), and support a subset of S3 api for operations on the object storage. The purpos of the first set of tests was to validate that the S3 API for the object storage was implemented correctly.

It was also requiered that the prototypes supported Federated Authentication through EduGAIN. So that users of HNSciCloud could ue there home Univercity credentials to access the services of HNSciCloud. The second set, consisted of tests to ensure correct beheviour of of this system.

During the first month of the project the prototype phase had not started yet. So I used the time to get up to speed on the project and learning the tools i was going to use for the tests. I ran S3 tests against CERNS openstack service.

In juli the first contractor made there platform avalrable for S3 tests. later in july T-systems and RHEA made there Federated Authentictaion portals avalable for testing. IBM never provided any Federated Authentication during my stay at CERN.

In june


No results will be presented as they are confidential.
* Backgroud 

** Object storage 
Object storage is a computer data storage architecture that manages data as objects, as opposed to other storage architectures like file systems which manage data as a file hierarchy and block storage which manages data as blocks within sectors and tracks. Each object typically includes the data itself, a variable amount of metadata, and a globally unique identifier.

S3 is an API for operations on the object storage, eg: creating a bucket (objects are organized into containers called buckets), uploading objects into the bucket, downloading objects from a bocket, deleting objects, etc.

** Federated Authentication and Single Sign-on
Federated Authentication Is the means of linking a persons identety to accounts and data stored accross multiple systems and organizations. Single Sign-on is a part of Federated Authentication that enables a service provider from one organization to delegate web based authentication to another organization. For example this allowes a CERN researcher to login to a HNScieCloud service managed by an external contractor using his CERN computing account.

EduGAIN is the Federated Authentication network that CERN and most Univerceties are part of.

* Test description
** S3 test

The S3 test consists on a script that attempts the following operations on specified S3 hosts:

    S3 authentication (access key + secret key)
    PUT
    GET
    GET with prefix matching
    GET chunk
    GET  multiple chunks

For more information, aswell as the davix based test script: https://gitlab.cern.ch/okeeble/s3test/tree/master

aws based s3test script: http://cern.ch/stikked/view/a326d01a

** Eudigan AAI
These tests relate to evaluating compliance with edugain login 
requirements. 

The following tests will be run manually:

#+ATTR_LATEX: :environment tabular  :align | r | p{7cm} | p{5cm} | 
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
|   | Tests                                                                                | Expected Result                                                     |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 1 | User attempts authentication from an eduGAIN IdP                                     | Authentication successful                                           |
|   | with R&S compliant attribute release                                                 |                                                                     |
|   |                                                                                      |                                                                     |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 2 | User attempts authentication from an eduGAIN IdP with insufficient attribute release | Authentication unsuccessful and helpful error page produced         |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 3 | User attempts authentication from multiple eduGAIN IdPs with credentials             | Authentication resolves to multiple,distinct users                  |
|   | sharing a common email address                                                       |                                                                     |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 4 | User accesses a permitted resource (e.g. tenant specific data)                       | Authenticated user is granted access                                |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 5 | User accesses a forbidden resource (e.g. tenant specific data)                       | Authenticated user is denied access                                 |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 6 | User is blocked by Admin                                                             | Admin is able to block an individual user                           |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 7 | Blocked user attempts authentication                                                 | Blocked user is denied access                                       |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|
| 8 | >10 users authenticate simultaneously                                                | Users authenticate in accordance with Reference Results (1) and (2) |
|   |                                                                                      |                                                                     |
|---+--------------------------------------------------------------------------------------+---------------------------------------------------------------------|


The tests will be documented in a table with following columns:
#+ATTR_LATEX: :environment tabular  :align |r|c|c|c|c| 
|------+-----+--------+--------------------+---------|
| test | idP | Result | Matches reference? | Comment |
|------+-----+--------+--------------------+---------|
|    1 |     |        |                    |         |
|------+-----+--------+--------------------+---------|
|    2 |     |        |                    |         |
|------+-----+--------+--------------------+---------|
|  ... |     |        |                    |         |


* Description of how the tests ware preformed

** S3 test
Setup
IBM

the davix client does not work with IBM, aws s3api was used instead. A modified version of the davix based script was used where all the davix commands ware replaced by equivalent aws s3api commands.


    Not yet possible for us to manage buckets, and access keys. So IBM created a test bucket emailed us the keys and endpoint url.
    Created a blumix VM  with the HN.sh comand line tool, with following parameters.
        CPU: 1
        Memory: 1024MB
        Image: CENTOS_LATEST_64
    Installed aws s3api, configured aws credentials with the keys and endpoint url received from IBM.
    executed the aws based s3test script.

RHEA
T-Systems

    Created a bucket in OBS section of MyWorkspace dashboard with following parameters:
        Class: Standard
    Created an ECS VM on MyWorkspace dashboard with following parameters:
        ECS type: General-Purpose
        vCPU: 1
        Memory: 4GB
        Image: Standard_CentOS_7_latest
    Installed davix client on the VM, cloned S3 endpoint test, and configured the s3 host to be the newly created bucket using the URL: s3://testbucket.obs.otc.t-systems.com
    Executed the script in S3 endpoint test repository


** Auth AAI tests
RHEA
Test 1

3 August 2017

    Using my CERN eduGAIN account an account was created on nuv.la following the instructions on: http://hn-prototype-docs.readthedocs.io/en/latest/administrator/index.html
    After receiving administrative rights, I successfully logged in to fed-id.nuv.la/auth/. Selecting CERN Realm and CERN IDP. There i was able to check the attributes of my user account against the R&S specification. The required R&S ware present and correct.

11 August 2017

Something changed and this test fails

    Using my CERN account attempted to login to fed-id.nuv.la. selecting CERN realm and CERN idp.
    After successfully being authenticated by CERN I am redirected to the IDP selection page on nuv.la rather then being granted access to the administration portal.

25 August 2017

The issue hove been , and the test passes again

(Serns SAML server does not support the Scope tag)
Test 3

4 August 2017

    In CERNs user settings portal I changed my primary email address to the email address of my KTH account.
    I attempted to login to fed-id.nuv.la using my CERN account, It authenticated successfully just like before the change. However It did not fetch the new email address from CERN idP, since this account was already registered in fed-id.nuv.la.
    I attempted to login to fed-id.nuv.la using my KTH account, It authenticated successfully just like before the change to a separate user from the previous one.
    This test is probably not valid, since there was already 2 accounts registered in fed-id.nuv.la one for my CERN account and one for my KTH account and the email address of the accounts was not updated. This test should probably be performed with 2 accounts never used to login to fed-id.nuv.la before.


Test 6 & 7

3 August 2017

    A Collogue used there CERN eduGain account to login to nuv.la and fed-id.nuv.la, following the instructions on: http://hn-prototype-docs.readthedocs.io/en/latest/administrator/index.html. Authentication of both web portals was successfully.
    Using my administrative account on fed-id.nuv.la I blocked my collogues account by adding it to the black list as described in http://hn-prototype-docs.readthedocs.io/en/latest/administrator/blacklisting.html
    My collogue used there blocked account to attempt a login to fed-id.nuv.la, authentication was unsuccessful.
    My collogue used there blocked account to attempt a login to. nuv.la,  Authentication was successful. (Is this intended?)


   
OTC
Test 1

15 August 2017

    Attempted To login through URL https://auth.otc.t-systems.com/authui/federation/websso?domain_id=3234c5a8b91040eb895dfa86a892ebf9&idp=CERN&protocol=saml
    Rederected To CERN authentication portal
    After authentication redirected to OTC webpage with error message:
    The browser detects that another contract is opening. This contract will be closed

#+LATEX: \bibliographystyle{plain}
#+LATEX: \bibliography{refs}

